### register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "nama":"aldii",
    "email":"200401141@student.umri.ac.id",
    "no_telp":"081368094422",
    "password":"password123"
}

### verify otp
POST http://localhost:3000/auth/verify-otp
Content-Type: application/json

{
    "email":"200401141@student.umri.ac.id",
    "otp":"739987"
}

#### resend otp
POST http://localhost:3000/auth/resend-otp
Content-Type: application/json

{
    "email":"200401141@student.umri.ac.id"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"200401141@student.umri.ac.id",
    "password":"aldi123"
}

### RESET PASSWORD
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
    "email":"200401141@student.umri.ac.id"
}

### CHANGE PASSWORD
PUT http://localhost:3000/auth/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjIwMDQwMTE0MUBzdHVkZW50LnVtcmkuYWMuaWQiLCJpYXQiOjE3MDEyNjMxNDN9.ENazShTzd6Z64sb2Y6vH6C3Jt-b-etVbx8yBLHUtNLQ
Content-Type: application/json

{
    "password":"aldi123",
    "confirmationPassword":"aldi123"
}

### GET USER BY TOKEN
GET http://localhost:3000/auth/whoami?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjIwMDQwMTE0MUBzdHVkZW50LnVtcmkuYWMuaWQiLCJpYXQiOjE3MDEyNjMxNDN9.ENazShTzd6Z64sb2Y6vH6C3Jt-b-etVbx8yBLHUtNLQ

### getAllAccount
GET http://localhost:3000/profile

### getAccountById
GET http://localhost:3000/profile/3

### updateProfilebyId
PUT http://localhost:3000/profile/updateProfile
Content-Type: application/json

{
    "account_id":1,
    "no_telp":"012345678910",
    "negara": "Indo",
    "kota": "jogya"
}
