### register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "nama":"aldii",
    "email":"200401141@student.umri.ac.id",
    "no_telp":"081368094422",
    "password":"password123",
    "ConfirmationPassword":"password123"
}

### verify otp
POST http://localhost:3000/auth/verify-otp
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjo0NSwiZW1haWwiOiIyMDA0MDExNDFAc3R1ZGVudC51bXJpLmFjLmlkIiwiaWF0IjoxNzAxODYyNTQ0fQ.JljK-AO405MyHBbokt8TFXKP64QSpd3HMYno-T8F1ic

{
    "otp":"140464"
}

#### resend otp
POST http://localhost:3000/auth/resend-otp
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjo0NSwiZW1haWwiOiIyMDA0MDExNDFAc3R1ZGVudC51bXJpLmFjLmlkIiwiaWF0IjoxNzAxODYyNTQ0fQ.JljK-AO405MyHBbokt8TFXKP64QSpd3HMYno-T8F1ic



### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"200401141@student.umri.ac.id",
    "password":"password123"
}

### RESET PASSWORD
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
    "email":"200401141@student.umri.ac.id"
}

### CHANGE PASSWORD
PUT http://localhost:3000/auth/reset-password
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjIwMDQwMTE0MUBzdHVkZW50LnVtcmkuYWMuaWQiLCJpYXQiOjE3MDE4NjMwMDZ9.NFLU-Mp2Z8dT-w5wz_T-UYMfFBvfi0Xer53wcL9r6y8

{
    "password":"aldi123",
    "confirmationPassword":"aldi123"
}

### GET USER BY TOKEN
GET http://localhost:3000/auth/whoami
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiYWEiLCJpYXQiOjE3MDE3NTI0MzZ9.NrhPTkc7m4Y-pxLZrlKgFf9fJwtp3C2TY4KaIubFxCU

### getAllAccount
GET http://localhost:3000/profile

### getAccountById
GET http://localhost:3000/profile/14

### updateProfilebyId
PUT http://localhost:3000/profile/14
Content-Type: application/json

{
    "no_telp":"012345678910",
    "negara": "Indo",
    "kota": "jogya"
}

### Change Password By Login
PUT http://localhost:3000/profile/changePassword
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiYWEiLCJpYXQiOjE3MDE3NTI0MzZ9.NrhPTkc7m4Y-pxLZrlKgFf9fJwtp3C2TY4KaIubFxCU

{
    "password_lama": "password123",
    "password_baru": "aldi123",
    "Confirmationpassword_baru": "aldi123"
}

### GetAllCourse
GET http://localhost:3000/course/

### AddCourse
POST http://localhost:3000/course/addCourse
Content-Type: application/json

{
    "title":"UI/UX untuk pemula",
    "mentor_id": 1,
    "deskripsi":"Course UI/UX untuk kamu mau yang baru mau mulai",
    "kategori_id":2,
    "harga":0,
    "premium":false,
    "level":"Beginner"
}

### GetCourseByCategory
GET http://localhost:3000/course/filter?kategori_id=1&kategori_id=3sort=created_at&order=asc